- name: Build wireguard-tools (wg) statically
        run: |
          git clone https://git.zx2c4.com/wireguard-tools
          cd wireguard-tools/src
          
          # 补充 RUNSTATEDIR 与系统头文件定义
          make -j$(nproc) \
            CC=arm-linux-gnueabi-gcc \
            LD=arm-linux-gnueabi-ld \
            CFLAGS="-O2 -static -DRUNSTATEDIR=\\\"/var/run\\\" -I../contrib/uapi/kernel-headers" \
            LDFLAGS="-static" \
            wg
            
          file wg
          cd ../..
